
project:
  type: book

lang: en


book:
  title: "Lab sessions : Stochastic Control and Machine Learning"
  author: "Samy Mekkaoui"
  date: today
  repo-url: "https://github.com/SamyMekk/TP-Controle-Stochastique"
  chapters:
     - index.qmd

     - part: "Part n°1 : Deep Learning for PDE"
       chapters:
         - contents/DeepPDE/RappelsDeepPDE.qmd
         - contents/DeepPDE/TP1.qmd
     - part: "Part n°2  : Reinforcement Learning for stochastic control problems"
       chapters:
         - contents/RL/RappelsRL.qmd 
         - contents/RL/TP2.qmd
     - part: "Part n°3 : Generative AI for data generation"
       chapters:
         - contents/GenerativeIA/RappelsGenAI.qmd
         - contents/GenerativeIA/TP3.qmd
 
     - references.qmd
     - appendix.qmd

    
     

  sidebar:
    style: docked

format:
  html:
    mainfont: "Computer Modern Serif"
    theme: cosmo 
    css: utils/styles.css
    include-before-body:
      - utils/macros
    toc: true
    sidebar: true 
 
  
bibliography : references.bib
nocite: |
  @*

execute:
  kernel : "these_env"
  echo: true


